name: Daily README Update

on:
  schedule:
    - cron: '07 19 * * *' 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |
        echo "Dernière mise à jour : $(date)" >> README.md
        git config --global user.name 'AlexandrePDA'
        git config --global user.email 'a.pires130@gmail.com'
        git add README.md
        git commit -m "Mise à jour quotidienne du README"
        git push
